### PR TITLE
Trim orthogonal build features + enforce style

### PR DESCRIPTION
**Pull request by anko**
This PR reduces build complexity and maintenance burden, by trimming away build features that are orthogonal to the goals of the library:

 - Remove the minification step. This is trivial for users to do, with [uglifyjs](https://github.com/mishoo/UglifyJS), [esmangle](https://github.com/estools/esmangle) or [closure compiler](https://developers.google.com/closure/compiler/). It's not a library's business what minifier they choose to use.
 - Remove browser builds. Tools for this such as [browserify](http://browserify.org/) and [webpack](https://webpack.github.io/) are widely available. Especially browserify is dead easy to use.
 - Forsake old IE (which doesn't have `forEach`). [Polyfills are widely available](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#Polyfill).
 - Enforce [standard style](http://standardjs.com/). Prevents bugs with unused-variable checks and makes sure PRs are up to scratch.

No functionality changes to the library itself.

What do you think?

### CODE REVIEW

**Comment by wavebeem** [comment]
I agree on all counts.

**Comment by anko** [comment]
@wavebeem https://github.com/jneen/parsimmon/commit/228799aa2743ba7f2e95ce8e007507a5b5f0c038 too? I only thought of `standard` after PRing and the list of fixups to get it to conform was pretty huge.

**Comment by wavebeem** [comment]
Oh. Not as sure of that one. It is a big diff. I won't bother weighing in on source style though.

**Comment by anko** [comment]
Further thoughts on this?

If you're hesitant about `standard`, feel free to just discard that last commit. It's completely separate from the rest of the cleanup.

**Comment by wavebeem** [comment]
Oh sorry, I meant to touch base on this one again. I would generally be in favor of doing this, but the browser test actually depends on this build existing.

@jneen Browser builds coming with parsimmon are a requirement, yes?

**Comment by wavebeem** [comment]
We're going to stick with IE7+ support, as well as keeping the browser (globals) builds. I think we may as well keep the .min.js build in that case since people expect it from browser friendly libs like jQuery.

Which leaves us with adding `standard`. I think in the future I may add some eslint rules to enforce aspects of the current style, but I don't think it's worth making changes to half the library to comply with `standard`.

Thanks for your work on this PR, but I think I'm going to decline.

**Comment by anko** [comment]
OK, no problem.

For others reading along who prefer simplicity and maintainability over convenience or backward-compat, maybe my fork [partser](https://github.com/anko/partser) is interesting. it's based on this PR, and [I've additionally](https://github.com/anko/partser/compare/a41d6dffcadccc2498fd23817499bfa68292672a...master)—

 - dropped chaining style in favour of exposing parsers as first-class functions (easier abstraction and composition),
 - dropped redundant base parsers like `seqMap` (trivially constructed from `seq` and `map`),
 - ported tests to [tape](https://github.com/substack/tape) ([TAP](https://en.wikipedia.org/wiki/Test_Anything_Protocol)-compat & maintainability), and
 - added a `replace` function for changing a parser's behaviour without altering its identity (for extreme use-cases like read-macros).

**Comment by wavebeem** [comment]
That sounds very cool. I'll have to keep my eye on it.

**Pull request closed without merging**
