### PR TITLE
Adding sepBy and sepBy1

### PR DESCRIPTION
**Pull request by hughfdjackson**
I've stolen the implementations pretty much wholesale from the haskell
implementation; so they may well not be optimal. :|

I've taken the liberty of bumping the version number and updating the changelog; feel free to tell me to roll that back if you'd prefer to release other features (assuming you're okay with adding this to the library). 

Addresses  #29

### CODE REVIEW

**Comment by jneen** [comment]
Yay!

**Comment by jneen** [comment]
if you could revert the bumps to the version - i like to only do that in release commits.

**Comment by jneen** [comment]
otherwise looks great, thank you!

**Comment by hughfdjackson** [comment]
:D hurrai - I'll update that now.

**Comment by hughfdjackson** [comment]
@jneen done, and squashed so no one has to put up with that mess in the history :)

**Comment by jneen** [comment]
Cool! CI is weird right now but it's relatively straightforward and tests pass locally so we are go.

**Pull request merged**
