### PR TITLE
Fix npm git install

### PR DESCRIPTION
**Pull request by freekh**
Added install step so it is possible (where make exists) to npm install git

### CODE REVIEW

**Comment by wavebeem** [comment]
I plan to migrate off of `make` eventually to something that better supports Windows, but this is a good start. I know I even stubbed my toe on this when I first installed the project. Thanks!

**Comment by wavebeem** [comment]
Oh, now that I think about it, this is a little weird. We're already publishing the built assets, so this should really be [prepublish](https://docs.npmjs.com/misc/scripts). But if that's gonna change, we kinda need to have a more npm-centric build setup...

**Comment by freekh** [comment]
Hm, yes, I suppose that is more correct. Will fix

**Comment by freekh** [comment]
Hmm, yes, prepublish seems more correct. I'll close this PR then and perhaps do another one when the moon and stars are in that special make2npm constellation :)

**Comment by wavebeem** [comment]
Thanks

**Comment by jneen** [comment]
Prepublish would make sense if npm stopped introspecting your .gitignore - checking in compiled artifacts is no fun.

**Comment by wavebeem** [comment]
It will ignore `.gitignore` if you add a `.npmignore` which is empty. That's how I solved it in https://github.com/wavebeem/battenberg

**Comment by jneen** [comment]
oh nice!

**Pull request closed without merging**
