### PR TITLE
Fixes #150; adds notFollowedBy

### LINKED ISSUE #150: Negative Lookahead
Hi, is there an idiomatic way to write a parser that only matches if it is not followed by another parser?

```js
const parseFoo = Parsimmon.string("foo");
const parseBar = Parsimmon.string("bar");
const parseFooNotFollowedByBar = ?;

parseFoo.then(parseBar).parse("foobar"); // should succeed
parseFooNotFollowedByBar.then(parseBar).parse("foobar"); // should fail
```
I suspect that lookahead could help here, but the documentation does not really help me:
> Parses using parser, but does not consume what it parses. Yields an empty string.

So it does not change the input and always returns the same thing. What is the difference to `() => ""`?

I do know that the example could easily be rewritten in an LL1 grammar that would be more efficient to parse. I'm just wondering whether parsimmon supports the approach of not matching if something else succeeds.

### PR DESCRIPTION
**Pull request by wavebeem**

### CODE REVIEW

**Comment by jneen** [comment]
Why an empty string in particular and not, for example, `null`?

**Comment by wavebeem** [comment]
For consistency with `lookahead` which was already implemented to return an empty string. I would be fine changing it though (and probably removing `lookahead`'s function overloads and return value whenever we go to 2.0).

**Comment by wavebeem** [comment]
@jneen Are you good with this after my explanation?

**Comment by jneen** [comment]
An empty string doesn't make sense here, and I don't think it makes sense in `lookahead` either. Since people are using this more for flow control than for value munging, I also don't buy a consistency argument. Let's do the thing that makes sense here, rather than doing something that doesn't make sense because we do things that don't make sense elswhere?

**Comment by wavebeem** [comment]
OK, I can change it for `notFollowedBy` then. `lookahead` has other issues that will need to be addressed with Parsimmon `2.0` like the function type overloading.

**Comment by jneen** [comment]
(We could also rename/alias `lookahead` to `followedBy` for interface consistency.)

**Comment by wavebeem** [comment]
Yeah, I'll write all of that up into an issue now!

**Comment by wavebeem** [comment]
Relevant criticisms opened in https://github.com/jneen/parsimmon/issues/156

**Comment by wavebeem** [comment]
This should be part of the release that includes https://github.com/jneen/parsimmon/issues/157

**Pull request merged**
